on:
  push:
    branches:
        - main
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{secrets.FTP_SERVER}}
        username: ${{secrets.FTP_USERNAME}}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /

   # - name: 🔄 Restart server
      #uses: appleboy/ssh-action@v0.1.6
      #with:
        #host: ${{ secrets.SSH_HOST }}
        #username: ${{ secrets.SSH_USERNAME }}
        #key: ${{ secrets.SSH_PRIVATE_KEY }}
        #script: |
            #cd /home/highpkui/kao_website/mysite/
            ## Activate the virtual environment if necessary
            ## source /home/username/virtualenv/mysite/3.8/bin/activate
            ## Restart the Python app or server
            #pkill -f "python app.py" || true
            #nohup python app.py &
